# Generated by Django 5.2.12 on 2026-03-17 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Appliance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('power_watts', models.FloatField(help_text='Power in Watts (P)')),
                ('length_m', models.FloatField(help_text='Length of wire in meters (L)')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appliances', to='auditor.project')),
            ],
        ),
    ]
