# Generated by Django 5.2.12 on 2026-03-17 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appliance',
            name='power_factor',
            field=models.FloatField(default=1.0, help_text='Power Factor (0.0 to 1.0)'),
        ),
        migrations.AlterField(
            model_name='appliance',
            name='power_watts',
            field=models.FloatField(help_text='Real Power in Watts (P)'),
        ),
    ]
