# Generated by Django 5.2.12 on 2026-03-17 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditor', '0002_appliance_power_factor_alter_appliance_power_watts'),
    ]

    operations = [
        migrations.AddField(
            model_name='appliance',
            name='appliance_type',
            field=models.CharField(choices=[('Motor/AC', 'Motor/AC'), ('Light', 'Light'), ('Standard', 'Standard')], default='Standard', max_length=20),
        ),
        migrations.AddField(
            model_name='appliance',
            name='quantity',
            field=models.IntegerField(default=1, help_text='Number of identical items on this circuit'),
        ),
        migrations.AddField(
            model_name='project',
            name='phase_type',
            field=models.CharField(default='1-Phase', max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='total_load',
            field=models.FloatField(default=0.0, help_text='Total Connected Load (W)'),
        ),
        migrations.AlterField(
            model_name='appliance',
            name='power_watts',
            field=models.FloatField(help_text='Real Power per item in Watts (P)'),
        ),
    ]
