# Generated by Django 5.2.12 on 2026-03-17 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditor', '0003_appliance_appliance_type_appliance_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appliance',
            name='hours_used_per_day',
            field=models.FloatField(default=8.0, help_text='Estimated usage per day in hours'),
        ),
    ]
