# Generated by Django 5.2.12 on 2026-03-17 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditor', '0004_appliance_hours_used_per_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='user_uid',
            field=models.CharField(blank=True, help_text='Firebase User UID', max_length=128, null=True),
        ),
    ]
